"""inicial

Revision ID: a9a261e130bf
Revises: 
Create Date: 2026-09-16 23:30:00.677542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# identificadores usados pelo Alembic para saber a ordem das migrações
revision: str = 'a9a261e130bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A Base de Conhecimento (RAG) guarda o embedding de cada item numa
    # coluna do tipo Vector (extensão pgvector) — precisa existir ANTES da
    # tabela "itens_de_conhecimento" ser criada, então entra logo no início
    # desta migração, antes de qualquer create_table gerado automaticamente.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('email_conta', sa.String(length=150), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_conta')
    )
    op.create_table('configuracoes_agente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome_do_agente', sa.String(length=100), nullable=False),
    sa.Column('contexto_da_empresa', sa.Text(), nullable=False),
    sa.Column('area_atuacao', sa.JSON(), nullable=False),
    sa.Column('endereco_cep', sa.String(length=15), nullable=True),
    sa.Column('endereco_rua', sa.String(length=150), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco_numero', sa.String(length=20), nullable=True),
    sa.Column('endereco_complemento', sa.String(length=100), nullable=True),
    sa.Column('endereco_detalhes_adicionais', sa.Text(), nullable=True),
    sa.Column('nome_do_template_encaminhamento', sa.String(length=150), nullable=False),
    sa.Column('nome_do_template_reengajamento', sa.String(length=150), nullable=False),
    sa.Column('nome_do_template_reencaminhamento', sa.String(length=150), nullable=False),
    sa.Column('nome_do_template_atencao', sa.String(length=150), nullable=False),
    sa.Column('roteiro_conversa', sa.Text(), nullable=False),
    sa.Column('responder_apenas_com_base_no_conhecimento', sa.Boolean(), nullable=False),
    sa.Column('mensagem_fora_do_escopo', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_agente_id_empresa'), 'configuracoes_agente', ['id_empresa'], unique=True)
    op.create_table('integracoes_saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome_da_conexao', sa.String(length=100), nullable=False),
    sa.Column('url_webhook', sa.String(length=500), nullable=False),
    sa.Column('chave_api', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_envio_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_envio_com_sucesso', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integracoes_saida_id_empresa'), 'integracoes_saida', ['id_empresa'], unique=False)
    op.create_table('integracoes_whatsapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_numero_telefone_meta', sa.String(length=50), nullable=False),
    sa.Column('id_waba_meta', sa.String(length=50), nullable=True),
    sa.Column('numero_exibicao', sa.String(length=30), nullable=True),
    sa.Column('token_de_acesso', sa.String(length=500), nullable=False),
    sa.Column('conectado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integracoes_whatsapp_id_empresa'), 'integracoes_whatsapp', ['id_empresa'], unique=True)
    op.create_table('itens_de_conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_de_conhecimento_id_empresa'), 'itens_de_conhecimento', ['id_empresa'], unique=False)
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('contato_nome', sa.String(length=150), nullable=False),
    sa.Column('contato_telefone', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_id_empresa'), 'setores', ['id_empresa'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hash_senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id_empresa'), 'usuarios', ['id_empresa'], unique=False)
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('RECEBIDO', 'EM_ATENDIMENTO', 'ENCAMINHADO', 'RESOLVIDO', name='status_atendimento'), nullable=False),
    sa.Column('id_setor', sa.Integer(), nullable=True),
    sa.Column('resumo_do_atendimento', sa.String(length=500), nullable=True),
    sa.Column('ultima_atividade_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reengajamento_por_silencio_enviado', sa.Boolean(), nullable=False),
    sa.Column('mensagens_livres_desde_ultimo_template', sa.Integer(), nullable=False),
    sa.Column('encaminhamento_definitivo', sa.Boolean(), nullable=False),
    sa.Column('houve_tentativa_de_manipulacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_setor'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id_empresa'), 'atendimentos', ['id_empresa'], unique=False)
    op.create_index(op.f('ix_atendimentos_status'), 'atendimentos', ['status'], unique=False)
    op.create_index(op.f('ix_atendimentos_whatsapp'), 'atendimentos', ['whatsapp'], unique=False)
    op.create_table('conversas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('apelido', sa.String(length=100), nullable=True),
    sa.Column('fixada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_atendimento'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_id_atendimento'), 'conversas', ['id_atendimento'], unique=False)
    op.create_index(op.f('ix_conversas_id_empresa'), 'conversas', ['id_empresa'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_conversa', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.Enum('CLIENTE', 'AGENTE_IA', 'ATENDENTE_HUMANO', 'SISTEMA', name='remetente_mensagem'), nullable=False),
    sa.Column('tipo_conteudo', sa.Enum('TEXTO', 'AUDIO', 'IMAGEM', 'DOCUMENTO', name='tipo_conteudo_mensagem'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('id_midia_whatsapp', sa.String(length=100), nullable=True),
    sa.Column('mime_type_da_midia', sa.String(length=100), nullable=True),
    sa.Column('nome_do_arquivo_da_midia', sa.String(length=255), nullable=True),
    sa.Column('id_mensagem_whatsapp', sa.String(length=100), nullable=True),
    sa.Column('status_entrega', sa.Enum('ENVIADA', 'ENTREGUE', 'LIDA', 'FALHOU', name='status_entrega_mensagem'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_mensagem_whatsapp', name='uq_mensagem_whatsapp')
    )
    op.create_index(op.f('ix_mensagens_id_conversa'), 'mensagens', ['id_conversa'], unique=False)
    op.create_index(op.f('ix_mensagens_id_mensagem_whatsapp'), 'mensagens', ['id_mensagem_whatsapp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_id_mensagem_whatsapp'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_id_conversa'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_conversas_id_empresa'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_id_atendimento'), table_name='conversas')
    op.drop_table('conversas')
    op.drop_index(op.f('ix_atendimentos_whatsapp'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_status'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_id_empresa'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_index(op.f('ix_usuarios_id_empresa'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_setores_id_empresa'), table_name='setores')
    op.drop_table('setores')
    op.drop_index(op.f('ix_itens_de_conhecimento_id_empresa'), table_name='itens_de_conhecimento')
    op.drop_table('itens_de_conhecimento')
    op.drop_index(op.f('ix_integracoes_whatsapp_id_empresa'), table_name='integracoes_whatsapp')
    op.drop_table('integracoes_whatsapp')
    op.drop_index(op.f('ix_integracoes_saida_id_empresa'), table_name='integracoes_saida')
    op.drop_table('integracoes_saida')
    op.drop_index(op.f('ix_configuracoes_agente_id_empresa'), table_name='configuracoes_agente')
    op.drop_table('configuracoes_agente')
    op.drop_table('empresas')
    # ### end Alembic commands ###
